### PR TITLE
1.20.1 Update

### PR DESCRIPTION
**Pull request by mrsterner**
- Updated dependency versions
- Fixed mappings
- Fixed Criterions
- Fixed Mixins
- Fixed tags

### CODE REVIEW

**Comment by mrsterner** [comment]
Three GameTests fail
- [x] requiem-test:requiemtestsuite/goldenapplescurezombies
- [x] requiem-test:possessionaitests/possessedmobscanttargetthemselves
- [x] requiem-test:vagrantplayertests/vagrantplayersdonottriggersculksensors

might need assist with those

**Comment by Pyrofab** [comment]
I see that you removed Haema compatibility, is it because the mod is not updated yet, or because it's not going to be updated ?

**Comment by mrsterner** [comment]
> I see that you removed Haema compatibility, is it because the mod is not updated yet, or because it's not going to be updated ?

It is indeed not gonna be updated

**Review by Pyrofab — APPROVED** [review]
Awesome, thanks for your contribution !

Also nice to see the mixins updated, MixinExtra certainly made things a lot easier for us.

**Pull request merged**
